### ISSUE TITLE
Add support for hiding bond pouch orb

### ISSUE THREAD

**Issue by dginovker** [wizguin/runelite-orb-hider#3] opened 2021-11-16 23:01 UTC
![image](https://user-images.githubusercontent.com/32943174/142079939-258c878b-b2fe-469b-a8a5-f34a8e73120b.png)

This is the orb I want to hide the most!

**Comment by wizguin** [comment] 2021-11-18 18:44
Duplicate of #2

**Closed as completed by wizguin** 2021-11-18 18:44 UTC
